site_name: cirkit
site_url: https://example.com
repo_url: https://github.com/april-tools/cirkit
nav:
  - Home: 'README.md'
  - Notebooks: 'notebooks/README.md'
  - API documentation: 'api/'
plugins:
  - search
  - autorefs
  - gen-files:
      scripts:
        - scripts/generate_api_pages.py
  - literate-nav:
      nav_file: overview.md
  - section-index
  - mkdocstrings:
      handlers:
        python:
          import:
            - https://docs.python.org/3/objects.inv
          options:
            docstring_style: google
            show_root_heading: true
            show_root_full_path: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            show_if_no_docstring: true
theme:
  name: "material"
  palette:
    primary: blue
    accent: orange
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.instant
    - search.highlight
    - search.suggest
    - toc.follow
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: "¤"
